Laboratorio Esercitazione 1
==================
Riassunto e analisi delle funzioni numpy
----------------------

In [4]:
from numpy  import *
a = arange(15).reshape(3, 5)
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Creata matrice da 3 righe e 5 colonne

In [9]:
a.ndim


2

dimensioni della matrice

In [10]:
a.size


15

numero elementi della matrice

In [12]:
b = array( [ (1.5,2,3), (4,5,6) ] )
b


array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

array trasforma n sequenze in array n-dimensionali

In [15]:
 A = array( [[1,1],[0,1]] )
B = array( [[2,0],[3,4]] )
A*B



array([[2, 0],
       [0, 4]])

In [16]:
dot(A,B)


array([[5, 4],
       [3, 4]])

arange zeros e one so funzioni utili che consentono di generare array desiderati senza inserire manualmente i valori.
rispettivamente zeros e one tutti 0 e 1, arange invece indicando intervallo e passo.

In [1]:
import numpy as np
b=np.arange(12).reshape(3,4)
b
b.min(axis=1)


array([0, 4, 8])

attraverso la funzione axis è possibile scegliere in base a quale asse applicare una determianta operazione

sugli arrray sono presenti altre funzioni di interesse ma che già abbiamo studiato nella slide learn x in y in particolar modo quelle relative all'accesso su array 


In [4]:
from numpy import *


In [5]:
punti=random.rand(100,2)

In [6]:
punti


array([[ 0.42300084,  0.41678629],
       [ 0.26105348,  0.87990356],
       [ 0.06527506,  0.59910716],
       [ 0.555986  ,  0.72264708],
       [ 0.15194172,  0.30468254],
       [ 0.93774678,  0.79638365],
       [ 0.59186759,  0.47607993],
       [ 0.37957217,  0.75624355],
       [ 0.55249329,  0.22755506],
       [ 0.9000241 ,  0.37875888],
       [ 0.3130707 ,  0.36016831],
       [ 0.93843233,  0.47092741],
       [ 0.41562182,  0.40898116],
       [ 0.13373347,  0.25242172],
       [ 0.09011352,  0.28354074],
       [ 0.50012132,  0.26042328],
       [ 0.35560574,  0.95294503],
       [ 0.51129286,  0.84417476],
       [ 0.36324654,  0.76847267],
       [ 0.8254599 ,  0.55543217],
       [ 0.36782018,  0.52864461],
       [ 0.48789686,  0.98508543],
       [ 0.71158579,  0.31879774],
       [ 0.14870438,  0.88067384],
       [ 0.07344479,  0.65433162],
       [ 0.09327947,  0.10327254],
       [ 0.38429555,  0.43243214],
       [ 0.51786471,  0.46103516],
       [ 0.39260268,

In [8]:
from pyplasm import *

Evaluating fenvs.py..
...fenvs.py imported in 0.011543 seconds


In [9]:
VIEW(STRUCT([MK(p) for p in punti]))

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0xadff64b8> >

![punti piazza](punti.png)


In [11]:
def larExtrude1(model,pattern):
    """ Simplicial model extrusion in accord with a 1D pattern """
    V, FV = model
    d, m = len(FV[0]), len(pattern)
    coords = list(cumsum([0]+(AA(ABS)(pattern))))
    offset, outcells, rangelimit = len(V), [], d*m
    for cell in FV:
        tube = [v + k*offset for k in range(m+1) for v in cell]
        cellTube = [tube[k:k+d+1] for k in range(rangelimit)]
        outcells += [reshape(cellTube, newshape=(m,d,d+1)).tolist()]
    outcells = AA(CAT)(TRANS(outcells))
    cellGroups = [group for k,group in enumerate(outcells) if pattern[k]>0]
    outVertices = [v+[z] for z in coords for v in V]
    outModel = outVertices, CAT(cellGroups)
    return outModel

In [12]:
model = [[0,0],[1,0],[0,1]], [[0,1,2]]
pattern = [1]

In [14]:
from larlib import *

/usr/local/lib/python2.7/dist-packages/larlib/larstruct.py:233: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  self.body = [item for item in data if item != None]


In [15]:
pattern = [1]*10
VIEW(STRUCT(MKPOLS((larExtrude1(model,pattern)))))

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0xabfdcd88> >

![esempio 1](p1.png)

In [16]:
V = [[0,0],[1,0],[2,0],[0,1],[1,1],[2,1],[0,2],[1,2],[2,2]]
FV = [[0,1,3],[1,2,4],[2,4,5],[3,4,6],[4,6,7],[5,7,8]]
model = larExtrude1((V,FV),4*[1,2,-3])
VIEW(EXPLODE(1,1,1.2)(MKPOLS(model)))

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0xac00a7a0> >

![esempio 2](p2.png)

In [18]:
model = larExtrude1( VOID, 10*[1] )
VIEW(EXPLODE(1.5,1.5,1.5)(MKPOLS(model)))
model = larExtrude1( model, 10*[1] )
VIEW(EXPLODE(1.5,1.5,1.5)(MKPOLS(model)))
model = larExtrude1( model, 10*[1] )
VIEW(EXPLODE(1.5,1.5,1.5)(MKPOLS(model)))

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0xacd5e848> >

![esempio 3](p3.png)

In [27]:
model = larExtrude1( VOID, 13*[1,-1] )
VIEW(EXPLODE(2,1.5,2)(MKPOLS(model)))
model = larExtrude1( model, 13*[1,2] )
VIEW(EXPLODE(1.5,3,1.5)(MKPOLS(model)))

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0xab9c1e60> >

![esempio 4](p4.png)